### PR TITLE
time series analysis

### PR DESCRIPTION
**Pull request by aspina7**
just getting started with time series - also including outbreak detection in the same section (cant seem to find a separate rmd for that - eventhough it appears in the bookdown version as a tab?)

### CODE REVIEW

**Review by nsbatra — APPROVED** [review]
Thanks for the update @aspina7 
There's an empty page named "endemic_corridor.rmd", but you can delete it or rename it as needed. You can make changes to which rmds are included in the _bookdown.yml

**Comment by nsbatra** [comment]
@aspina7 do you want me to wait on merging this PR, or can I merge and you add more later?

**Comment by aspina7** [comment]
Gonna keep going on this branch - will ping you when done thanks!

**Comment by aspina7** [comment]
hey @nsbatra done with this draft now. 
wondering if @tjtnew you might have time to take a quick look at [this](https://github.com/nsbatra/Epi_R_handbook/blob/35da693d68c0f193adba888b4f3104599e52c8f1/new_pages/time_series.Rmd) please? Used a lot of {trending} and hoping did it right. 
Realise is a very chunky page, so grateful for any pointers!

**Comment by tjtnew** [comment]
@aspina7 no problem.  I'll take a look on Wednesday and get back to you.

**Comment by nsbatra** [comment]
@aspina7 
Am getting an error trying to knit saying that plotNA.imputations() has been replaced by ggplot_na_imputation.
image

**Comment by aspina7** [comment]
> Am getting an error trying to knit saying that plotNA.imputations() has been replaced by ggplot_na_imputations().
sorry - looks like didnt have the latest package version. Have now updated all the packages on the page and runs on my end.

@tjtnew is it okay if we merge this merge? and then you could leave comments/feedback [here](https://github.com/nsbatra/Epi_R_handbook/issues/91) or alternatively start a new pr with suggest pages please? Thanks a bunch!

**Comment by tjtnew** [comment]
yep - no probs

**Comment by nsbatra** [comment]
This is a great page Alex, thanks so much. Merging now so that other folks who are doing reviews can see this page "live" and give comments too in the Issue. 
I will likely make some minor formatting changes to align it with the other pages (e.g. removing tabsets so that in the offline version it can all be searchable). And I'm going to add "Outbreak detection" to the page title.

And thank you very much @tjtnew, looking forward to your insights!

**Pull request merged**
